apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirng-gen-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirng-gen
  template:
    metadata:
      labels:
        app: stirng-gen
    spec:
      containers:
        - name: stirng-gen
          image: devhlb/string-generator:1.0.1
